<div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
             
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="http://localhost/Lekcije/Lesson4/mvc-app/">Naslovnica</a></li>
                  <li><a href="http://localhost/Lekcije/Lesson4/mvc-app/form">Prijavi se</a></li>
                <li><a href="http://localhost/Lekcije/Lesson4/mvc-app/admin">Admin</a></li> 
                </ul>
              </nav>
            </div>
          </div>
            
    <div class="container">

      <form class="form-signin">
        <h2 class="form-signin-heading">Molimo vas, prijavite se.</h2>
        <label for="inputEmail" class="sr-only">Email adresa</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Lozinka</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Zapamti me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Prijavi se</button>
      </form>

    </div> <!-- /container -->
