<div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
             
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="http://localhost/Lekcije/Lesson4/mvc-app/">Naslovnica</a></li>
                  <li><a href="http://localhost/Lekcije/Lesson4/mvc-app/form">Prijavi se</a></li>
                <li><a href="http://localhost/Lekcije/Lesson4/mvc-app/admin">Admin</a></li> 
                </ul>
              </nav>
            </div>
          </div>


<form method="POST" action="http://localhost/Lekcije/Lesson4/mvc-app/form/submit" enctype="multipart/form-data">
        <fieldset>
        <legend>Osobne informacije:</legend>
        
        <label>Ime i prezime</label></br>
        <input type="text" name="name"/>
        <br><br>
        
        <label>Mail adresa</label></br>
        <input type="text" name="email"/>
        <br><br>
       
        <label>Smjer</label></br>
        <input type="text" name="smjer"/>
        <br><br>
        

        <label>Godina studija</label></br>
        <input type="radio" name="godina" value="1">1</br>
        <input type="radio" name="godina" value="2">2</br>
        <input type="radio" name="godina" value="3">3</br>
        <input type="radio" name="godina" value="4">4</br>
        <input type="radio" name="godina" value="5">5</br>
        <br><br>
  
        <label>Što te motiviralo da se prijaviš?</label></br>
        <textarea name="motivacija" rows="5" cols="20">
        </textarea></br>
        
        <label>Imaš li predznanje vezano uz web development?</label></br>
        <textarea name="predznanje" rows="5" cols="20">
        </textarea></br>
        
        

        <label>U kojim jezicima si do sada programirao?</label></br>
        <input type="checkbox" name="program" value="C#">C#<br>
        <input type="checkbox" name="program" value="JAVA">JAVA<br>
        <input type="checkbox" name="program" value="C++">C++<br>
        <input type="checkbox" name="program" value="C">C<br>
        <input type="checkbox" name="program" value="Python">Python<br>
        </br>

        <label>Uploadaj primjer svoga koda:</label></br>
        <input type="file" name="fileToUpload" id="fileToUpload"></br></br>
        <input type="submit" value="Submit" name="submit">
     
        </fieldset>
    </form>