 
  <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
             
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="http://localhost/Lekcije/Lesson4/mvc-app">Naslovnica</a></li>
                  <li><a href="form\index">Prijavi se</a></li>
                <li><a href="admin.php">Admin</a></li> 
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">PHP Akademija.</h1>
            <p class="lead">U suradnji s FERIT-om, po prvi puta ove godine, Inchoo organizira PHP akademiju. Želimo pomoći svim zaljubljenicima u kod da dobiju što više konkretnog znanja, kao i upoznati ih s Inchooerima i našim načinom rada. Predavanja koja će trajati 5 tjedana imaju za cilj ohrabriti mlade nade koje vole kodirati, posebice one koje se već neko vrijeme vide u Inchoou.</p>
             <p class="lead">    Kroz predavanja ćemo sve polaznike pripremiti za rad na praktičnim projektima, a najbolji će dobiti i priliku da se dokažu i potencijalno zaposle u Inchoou.</p>
             <p class="lead">Imajte na umu da akademija zahtijeva vrijeme i angažman te da će polaznici prije same akademije proći proces selekcije kako bi se osigurala što veća kvaliteta rada. Na žalost, ne možemo vas primiti sve, no tko zna – možda u dogledno vrijeme budemo i na vašem faksu.</p>
              <p class="lead"> PHP akademija je koncipirana da se kroz nju uči i radi no to vas ne treba uplašiti. Čak štoviše, nadamo se da će vas upravo to motivirati! Predavači iz Inchooa će vas voditi kroz sve vježbe te raditi s vama kako bi svi mogli jednako kvalitetno pratiti predavanja. Program akademije će obuhvatiti lekcije iz web developmenta, a na vama će biti da rješavate domaće zadaće i vježbe.</p>
            </p>
          </div>

          

        </div>

      </div>

    </div>

   