<div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
             
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="http://localhost/Lekcije/Lesson4/mvc-app/">Naslovnica</a></li>
                  <li><a href="http://localhost/Lekcije/Lesson4/mvc-app/form">Prijavi se</a></li>
                <li><a href="http://localhost/Lekcije/Lesson4/mvc-app/admin">Admin</a></li> 
                </ul>
              </nav>
            </div>
          </div>  

<div class="container">

      <div class="starter-template">
        <h1>Uspješna prijava!</h1>
        <p class="lead"><a href="http://localhost/Lekcije/Lesson4/mvc-app/">Povratak na naslovnicu.</a></p>
      </div>

    </div><!-- /.container -->